version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Athens
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Athens
  open-pull-requests-limit: 10
